version: '3.8'
services:
  frontend:
    build:
      context: ../Tinder-Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=''
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
